syntax = "proto3";
package ProtoMessage;
option java_package = "com.yongyoung.dream";
option java_multiple_files = true;
option java_outer_classname = "MapProto";
option go_package="message";
//import "Player.proto";


//同步玩家数据
message MapSyncResponse{
    int64 playerId                          = 1; //玩家id
    int32 posX                              = 2; //位置X
    int32 posZ                              = 3; //位置Z
}

//请求移动
message MapPosRequest{
    int64 playerId                          = 1; //玩家id
    int32 posX                              = 2; //位置X
    int32 posZ                              = 3; //位置Z
}
//移动返回
message MapPosResponse{
    int64 playerId                          = 1; //玩家id
    int32 posX                              = 2; //位置X
    int32 posZ                              = 3; //位置Z
}


//游戏准备

// World map viewport request. Known revisions allow incremental responses.
message WorldChunkVersion {
    int32 chunkX = 1;
    int32 chunkZ = 2;
    int64 revision = 3;
}
message WorldViewportRequest {
    int32 minChunkX = 1;
    int32 maxChunkX = 2;
    int32 minChunkZ = 3;
    int32 maxChunkZ = 4;
    repeated WorldChunkVersion knownChunks = 5;
}
message WorldTileInfo {
    int32 localX = 1;
    int32 localZ = 2;
    int32 type = 3;
    int32 level = 4;
    int64 ownerId = 5;
}
message WorldBlockInfo {
    int32 blockX = 1;
    int32 blockZ = 2;
    repeated WorldTileInfo tiles = 3;
}
message WorldChunkInfo {
    int32 chunkX = 1;
    int32 chunkZ = 2;
    int64 revision = 3;
    repeated WorldBlockInfo blocks = 4;
}
message WorldVillageInfo {
    int32 villageId = 1;
    string name = 2;
    int32 posX = 3;
    int32 posZ = 4;
    string prefab = 5;
    int32 tileRadius = 6;
    int64 food = 7;
    int32 people = 8;
}
message WorldViewportResponse {
    repeated WorldChunkInfo chunks = 1;
    repeated WorldVillageInfo villages = 2;
    int64 serverTime = 3;
    int64 nextVillageRefreshAt = 4;
}

message GameStartRequest{
    int64 playerId                  	= 1; //玩家id
}


//游戏开始
message GameStartResponse{
    int64 playerId                  	= 1; //玩家id
    repeated HeroInfo selfHeros             = 2; //英雄信息
    repeated HeroInfo otherHeros            = 3; //英雄信息
    int32 flag				                = 4; //阵营
    int64 time                        = 5; //时间
}



//英雄列表请求
message HeroListRequest{
    int64 playerId                  	= 1; //玩家id
    repeated HeroInfo item                  = 2; //英雄信息
    int32 flag				= 3; //阵营
}


//英雄列表返回
message HeroListResponse{
    int64 playerId                  	= 1; //玩家id
    repeated HeroInfo item                  = 2; //英雄信息
    int32 flag				= 3; //阵营
}


//英雄信息
message HeroInfo{
    int64 playerId                          = 1; //玩家id
    int64 heroId                            = 2; //英雄id
    int64 heroCfgId                         = 3; //配置id
    int32 posX                              = 4; //位置X
    int32 posZ                              = 5; //位置Z
}


//英雄位置请求
message HeroPosRequest{
    int64 playerId                  	= 1; //玩家id
    HeroInfo item                  = 2; //英雄信息
}

//英雄位置返回
message HeroPosResponse{
    int64 playerId                  	= 1; //玩家id
    HeroInfo item                  = 2; //英雄信息
}

// 射门请求
message ShootBallRequest{
    int64 playerId = 1;  //玩家id
    int64 heroId = 2;    //英雄id
    int32 posX = 3;      //位置X
    int32 posZ = 4;      //位置Z
}

// 射门返回
message ShootBallResponse{
    int64 playerId = 1;  //玩家id
    int64 heroId = 2;    //英雄id
    int32 posX = 3;      //位置X
    int32 posZ = 4;      //位置Z
}

// 得分请求
message GameScoreRequest{
    int64 playerId = 1;  //玩家id
    int32 flag = 2;      //得分方
}

// 得分返回
message GameScoreResponse{
    int64 playerId = 1;  //玩家id
    int32 flag = 2;      //得分方
    int32 score = 3;     //得分
}

// 游戏结束返回
message GameOverResponse{
    int64 playerId = 1;  //玩家id
    int32 flag = 2;      //胜利方
}

// 塔防地格信息
message SlotInfo{
	int32 level = 5; // building level
	string instanceId = 6; // stable building instance id
	int64 attributeValue = 7; // effective configured building attribute
	int32 posX = 1;		//地块坐标X
	int32 posZ = 2;		//地块坐标Z
	int32 slotType = 3; //地块类型
	int32 defenser = 4;	//防御者
}

// 塔防地块信息
message SlotSetRequest{
	int64 playerId = 1;	//玩家id
	int32 type = 2;   	//操作类型：1、填加，  2、删除
	SlotInfo info = 3; 	//地块信息
}

// 塔防地块信息
message SlotSetResponse{
	bool success = 4;
	string error = 5;
	int64 food = 6;
	int32 people = 7;
	int64 playerId = 1;	//玩家id
	int32 type = 2;   	//操作类型：1、填加，  2、删除
	SlotInfo info = 3; 	//地块信息
}
